### PR TITLE
cool things i did while hiking this morning

### PR DESCRIPTION
**Pull request by jdadonut**
check out this cool clip from my hiking adventure this morning

https://user-images.githubusercontent.com/47060357/150051489-46720018-e03c-4577-b35d-ab0103397655.mp4

### CODE REVIEW

**Comment by mugman174** [comment]
sync that commit I just made into your branch

**Comment by jdadonut** [comment]
> sync that commit I just made into your branch then I will check and do

done

**Comment by mugman174** [comment]
okay but idk bc there's no actual code changes and stuff, just makefile stuff

**Comment by jdadonut** [comment]
> okay but idk bc there's no actual code changes and stuff, just makefile stuff

image
these commits are code

**Comment by mugman174** [comment]
ok gonna merge hope this doesn't break everything

**Pull request merged**
